export enum TenantSectionTitlesEnum {
  GENERAL_DETAILS = 'General Details',
  BRAND_AND_THEMING = 'Brand & Theming',
  AI_SERVICES = 'AI Services',
  PROVIDER_FEATURE_FLAGS = 'Recruitment Provider Features',
  SSO = 'SSO',
  DOCUMENTS = 'Documents',
  DOCUMENT_GROUPS = 'Group Types',
  EXTRACTION = 'Extraction',
  UI_CONFIG = 'UI Configuration',
  TALENT_AUTOMATION = 'Talent Automation',
  MATCHING_CONTROLS = 'Matching Controls',
  AUTO_REPLACEMENT = 'Auto-Replacement',
  SCORING_TEMPLATES = 'Scoring Templates',
  CONNECTOR_SETTINGS = 'Connector Settings',
  CLIENT_PIPELINE = 'Client Pipeline',
  CANDIDATE_IMPORT_SOURCES = 'Candidate Import Sources',
  PROVIDER_QUOTAS = 'Provider Quotas',
  CANDIDATE_DELIVERY = 'Candidate Delivery',
}
