export const formFieldNames = {
  generalDetails: {
    companyName: 'company_name',
    domain: 'domain',
    chatStrategy: 'chat_strategy',
    integrations: 'integrations',
  },
  settings: {
    preferredCurrency: 'settings.preferred_currency',
    preferredTimezone: 'settings.preferred_timezone',
    theme: 'settings.theme',
    themeColor: 'settings.theme_color',
    defaultThemeMode: 'settings.default_theme_mode',
    logos: {
      light: 'settings.logos.light',
      dark: 'settings.logos.dark',
    },
    hasDarkLogo: 'settings.has_dark_logo',
  },
  sso: {
    type: 'sso_config.type',
    enabled: 'sso_config.enabled',
    tenantId: 'sso_config.tenant_id',
    clientId: 'sso_config.client_id',
    clientSecret: 'sso_config.client_secret',
    scopes: 'sso_config.scopes',
  },
  aiConfig: {
    aiType: 'ai_config.open_ai_type',
    aiEmbeddingModel: 'ai_config.open_ai_embedding_model',
    temperature: 'ai_config.temperature',
    openAiKey: 'ai_config.open_ai_key',
    openAiEndpoint: 'ai_config.open_ai_endpoint',
    openAiVersion: 'ai_config.open_ai_version',
    webSearch: 'ai_config.web_search',
  },
  matchConfig: {
    topK: 'match_config.top_k',
    showAiCopilot: 'match_config.show_ai_copilot',
    showRankExplanation: 'match_config.show_rank_explanation',
    programmaticWeight: 'match_config.programmatic_weight',
    llmSemanticWeight: 'match_config.llm_semantic_weight',
    embeddingSimilarityWeight: 'match_config.embedding_similarity_weight',
    scoreThreshold: 'match_config.score_threshold',
    screeningModel: 'match_config.screening_model',
    deepModel: 'match_config.deep_model',
    screeningThreshold: 'match_config.screening_threshold',
    calibrationMode: 'match_config.calibration_mode',
    calibrationTopKMultiplier: 'match_config.calibration_top_k_multiplier',
    autoMatchOnJobIngest: 'match_config.auto_match_on_job_ingest',
    autoMatchOnCandidateIngest: 'match_config.auto_match_on_candidate_ingest',
  },
  extractionConfig: {
    includeReasoning: 'extraction_config.include_reasoning',
  },
  talentAutomation: {
    screeningEnabled: 'talent_automation_config.screening_enabled',
    enrichmentEnabled: 'talent_automation_config.enrichment_enabled',
    rerouteEnabled: 'talent_automation_config.reroute_enabled',
    interviewPrepEnabled: 'talent_automation_config.interview_prep_enabled',
    confidenceThreshold: 'talent_automation_config.confidence_threshold',
    hitlRequiredForRejection: 'talent_automation_config.hitl_required_for_rejection',
    screeningSlaSeconds: 'talent_automation_config.screening_sla_seconds',
    maxRerouteSuggestions: 'talent_automation_config.max_reroute_suggestions',
    interviewPrepQuestionCount: 'talent_automation_config.interview_prep_question_count',
  },
  documents: {
    documentTypes: 'document_types',
    documentDataSources: 'document_data_sources',
  },
  documentGroups: {
    name: 'name',
    description: 'description',
    metadata: 'metadata',
  },
  users: {
    email: 'email',
    firstName: 'first_name',
    lastName: 'last_name',
    password: 'password',
    role: 'role',
    accountId: 'account_id',
  },
};

export const CUSTOM_THEME_REQUIRED_VALIDATION = {
  [formFieldNames.settings.logos.light]: true,
  [formFieldNames.settings.logos.dark]: true,
  [formFieldNames.settings.defaultThemeMode]: true,
  [formFieldNames.settings.themeColor]: true,
};
